modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Deepseasaltyfish/ExternalView-Reloaded"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Deepseasaltyfish/ExternalView-Reloaded"
logoFile="logo.png"
credits="Ported to 1.21 NeoForge by SaltyFish."
authors = "FrozeRain, AgniaEndie, EVgenyGP, Endienasg, Senko-san, SaltyFish"
description='''
Mod that changes the distance of the camera from the player in third person mode.
'''
side="CLIENT"


[[mixins]]
config="${mod_id}.mixins.json"


[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
